version: '3.9'
services:

  qam_sdn_controller:
        restart: unless-stopped
        container_name: qam_sdn_controller
        image: qam_sdn_controller:0.0.1
        ports:
         - 8081:8081
         - 8181:8181
        networks:
           qameleon_network:
             ipv4_address: 172.10.12.2

  pce:
        ports:
            - '1234:1234'
        container_name: pce
        image: 'pce:0.0.1'
        networks:
           qameleon_network:
             ipv4_address: 172.10.12.3
  
  openroadm_sdn_agent:
        ports:
            - '830:830'
        image: 'mh-roadm:emulated'
        networks:
           qameleon_network:
             ipv4_address: 172.10.12.4


  netconf-testtool:
        ports:
            - '17830-17837:17830-17837'
        container_name: netconf_testtool_1.7.2
        image: 'netconf-testtool:1.7.2'
        networks:
           qameleon_network:
             ipv4_address: 172.10.12.5



networks:
  qameleon_network:
    ipam:
      config:
        - subnet: 172.10.12.0/24



